# Site
repository: samaracomacento/curriculo
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sâmara Antero
title: Arquiteta e Urbanista - CAU/RJ A172270-0
email: samaracomacento@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: saams.com.br
#website_title: Website ilustração

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: MushRoom Ilustrações
#  icon: https://saams.com.br/assets/favicon.png
#  url: https://saams.com.br
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

 # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
 #   - Lists
 #   - Tables
 #   - <a href="google.com">Links</a>
 #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Formação
    layout: list
    content:
      - layout: top-right
        title: Universidade Federal do Rio de Janeiro
        sub_title: Arquitetura e Urbanismo
        caption: 2011 - 2018
        description: | # this will include new lines to allow paragraphs
          Escola de Permacultura: Arquitetura como um organismo vivo e de memória
          Restauração e Reabilitação de uma ruína na Rua do Teatro - Centro RJ
      - layout: top-right
        title: Universidade do Estado do Rio de Janeiro
        sub_title: Aperfeiçoamento em Materiais e Técnicas de Construção Sustentáveis e Populares - NATEP
        caption: 2021
        description: | # this will include new lines to allow paragraphs
          Projeto Biblioteca Comunitária em Tanguá/RJ
      - layout: top-right
        title: UniPermacultura
        sub_title: Certificação de Design em Permacultura (PDC)
        caption: 2018
        #quote: >
        #  Short institution or course description (optional)
      - layout: top-right
        title: FAETEC/RJ
        sub_title: Técnico em Edificações
        caption: 2007 - 2009
        description: | # this will include new lines to allow paragraphs
          Casa eco-adaptada popular
  - title: Experiência
    layout: list
    content:
      - layout: right
        title: SAMN
        quote: >
          Associação Amigos do Museu Nacional da UFRJ
        sub_title: Consultora em Arquitetura
        caption: 2018 - atual
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura, projeto executivo, As Built, paisagismo, acompanhamento de obras, licenciamento, termo de referência. Arquitetura institucional, arquitetura efêmera, laboratórios, patrimônio histórico.
      - layout: right
        title: ETU/UFRJ
        quote: >
          Divisão de Imóveis Tombados do Escritório Técnico da Universidade
        sub_title: Estágio em Arquitetura
        caption: 2016 - 2018
        description: | # this will include new lines to allow paragraphs
          Levantamento e mapeamento de danos em edifícios do patrimônio histórico da UFRJ. Colaboração no levantamento e mapeamento do Jardim das Princesas, salas históricas e expansão das exposições - Museu Nacional/UFRJ. Colaboração no mapeamento do IFCS/UFRJ.
      - layout: right
        title: DiGiacomo
        quote: >
          DiGiacomo Engenheiros Associados
        sub_title: Estágio em Edificações
        caption: 2009 - 2010
        description: | # this will include new lines to allow paragraphs
          Desenho de habitações unifamiliares, As Built, projetos complementares.
  - title: Projetos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Laboratório de Coleções Líquidas
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #link_text: Link Text
        #additional_links:
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Laboratório de Manuseio de Coleções em Meio Líquido - Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O laboratório de manuseio de Coleções em meio líquido tem o objetivo de manter seguras as Coleções de espécimes conservados em álcool.
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura e acompanhamento de obra.
      - layout: left
        title: Laboratório de Taxidermia
        quote: >
          Laboratório de Taxidermia - Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O prédio laboratório de taxidermia foi projetado para dar um espaço de apoio para montagem e manuseio de espécimes.
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura e acompanhamento de obra.
  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #    Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
