# Site
repository: samaracomacento/curriculo
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sâmara Antero
title: Arquiteta e Urbanista - CAU/RJ A172270-0
email: samaracomacento@gmail.com
email_title: Contato
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: samaracomacento.github.io/curriculo/
website_title: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: MushRoom Ilustrações
#  icon: https://saams.com.br/assets/favicon.png
#  url: https://saams.com.br
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Arquiteta e Urbanista pela FAU/UFRJ, com 7 anos de experiência na elaboração e análise de projetos de arquitetura, licenciamento, acompanhamento de obras e elaboração termos de referência de caráter institucional. Atualmente colaboro em projetos de arquitetura para laboratórios de pesquisa, armazenamento de coleções cientificas, paisagismo e patrimônio histórico para o Museu Nacional/UFRJ.

 # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
 #   - Lists
 #   - Tables
 #   - <a href="google.com">Links</a>
 #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Formação
    layout: list
    content:
      - layout: top-right
        border: weak
        title: Arquitetura e Urbanismo
        sub_title: Universidade Federal do Rio de Janeiro
        caption: 2011 - 2018
        description: | # this will include new lines to allow paragraphs
          Escola de Permacultura: Arquitetura como um organismo vivo e de memória
          Restauração e Reabilitação de uma ruína na Rua do Teatro - Centro RJ.
      - layout: top-right
        border: weak
        title: Aperfeiçoamento em Materiais e Técnicas de Construção Sustentáveis e Populares
        sub_title: Universidade do Estado do Rio de Janeiro - NATEP
        caption: 2021
        description: | # this will include new lines to allow paragraphs
          Projeto Biblioteca Comunitária em Tanguá/RJ.
      - layout: top-right
        border: weak
        title: Certificação de Design em Permacultura (PDC)
        sub_title: UniPermacultura
        caption: 2018
        #quote: >
        #  Short institution or course description (optional)
      - layout: top-right
        title: Técnico em Edificações
        sub_title: FAETEC/RJ
        caption: 2007 - 2009
        description: | # this will include new lines to allow paragraphs
          Casa eco-adaptada popular.
  - title: Experiência
    layout: list
    content:
      - layout: right
        border: weak
        title: SAMN
        quote: >
          Associação Amigos do Museu Nacional da UFRJ
        sub_title: Consultora em Arquitetura
        caption: 2018 - atual
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura, projeto executivo, As Built, paisagismo, acompanhamento de obras, licenciamento, termo de referência. Arquitetura institucional, arquitetura efêmera, laboratórios, patrimônio histórico.
      - layout: right
        border: weak
        border: weak
        title: ETU/UFRJ
        quote: >
          Divisão de Imóveis Tombados do Escritório Técnico da Universidade
        sub_title: Estágio em Arquitetura
        caption: 2016 - 2018
        description: | # this will include new lines to allow paragraphs
          Levantamento e mapeamento de danos em edifícios do patrimônio histórico da UFRJ. Colaboração no levantamento e mapeamento do Jardim das Princesas, salas históricas e expansão das exposições - Museu Nacional/UFRJ. Colaboração no mapeamento do IFCS/UFRJ.
      - layout: right
        title: DiGiacomo
        quote: >
          DiGiacomo Engenheiros Associados
        sub_title: Estágio em Edificações
        caption: 2009 - 2010
        description: | # this will include new lines to allow paragraphs
          Desenho de habitações unifamiliares, As Built, projetos complementares.
  - title: Projetos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Laboratório de Coleções Líquidas
        caption: 2020 - Atual
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #link_text: Link Text
        #additional_links:
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Laboratório de Manuseio de Coleções em Meio Líquido - Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O laboratório de manuseio de Coleções em meio líquido tem o objetivo de manter seguras as Coleções de espécimes conservados em álcool.
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura, acompanhamento de obra e licenciamento.
      - layout: left
        border: weak
        title: Laboratório de Taxidermia
        caption: 2022 - 2025
        quote: >
          Laboratório de Taxidermia - Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O prédio laboratório de taxidermia foi projetado para dar um espaço de apoio para montagem e manuseio de espécimes.
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura, acompanhamento de obra e licenciamento.
      - layout: left
        border: weak
        title: Casa de Vegetação
        caption: 2024 - Atual
        quote: >
          Espaço para produção de mudas e experimentos botânicos - Horto Botânico do Museu Nacional/UFRJ.
        description: | # this will include new lines to allow paragraphs
          Projeto de reforma e acompanhamento de obra.
      - layout: left
        title: Laboratório de Coleções Secas
        border: weak
        caption: 2022
        quote: >
          Laboratório de Manuseio de Coleções Secas - Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O prédio laboratório de manuseio de coleções secas tem o objetivo de manter seguras as Coleções secas do Museu Nacional/UFRJ junto a uma infraestrutura de preparação e curadoria.
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura.
      - layout: left
        title: Teatro do Colégio Pedro II Niterói
        border: weak
        caption: 2021
        quote: >
          Colaboração na reforma do Teatro do Colégio Pedro II - Campus Niterói
        description: | # this will include new lines to allow paragraphs
          Documentação de Projeto Executivo.
      - layout: left
        border: weak
        title: Módulos Laboratoriais
        caption: 2019
        quote: >
           Prédio de Módulos emergencial para laboratórios de pesquisa - Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O prédio de módulos laboratoriais tem objetivo de atender uma demanda de laboratórios de diversos departamentos que encontraram-se sem locação fixa após o incêndio de 2018.
        description: | # this will include new lines to allow paragraphs
          Anteprojeto de arquitetura.
      - layout: left
        title: Módulos Administrativos
        caption: 2018 - 2020
        quote: >
          Prédio de Módulos emergencial para Administração do Campus de Pesquisa e Ensino do Museu Nacional/UFRJ. O prédio de módulos administrativos tem objetivo de atender uma demanda de espaços por diversos setores que encontraram-se sem locação fixa após o incêndio de 2018. O projeto foi pensado para ter uma construção mais rápida e garantir conforto ambiental e um ambiente agradável para os usuários. 
        description: | # this will include new lines to allow paragraphs
          Projeto de arquitetura e licenciamento.
  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #    Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
